apiVersion: v1
kind: Pod
metadata:
  name: phaedra2-parent
  labels:
    ci: phaedra2-parent-build
spec:
  containers:
   - name: builder
     image: 196229073436.dkr.ecr.eu-west-1.amazonaws.com/openanalytics/phaedra2-build-container:latest
     securityContext:
        privileged: true

